### ISSUE TITLE
How do we add owners to the subscription

### ISSUE THREAD

**Issue by girishgouda** [Azure-Samples/create-azure-subscription-dotnet-core#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

Currently the API call creates a subscription with none as owners. we want to add users or service principal as owner to the subscription

**Comment by jlian** [comment]
Hi, you need to pass in a list of AAD object IDs. See https://docs.microsoft.com/en-us/rest/api/resources/subscriptionfactory/createsubscriptioninenrollmentaccount#subscriptioncreationparameters
